<Box01>:
    canvas:
        Color:
            rgb: 1,1,1
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint: .8,1
        canvas:
            Color:
                rgb: 0.9,0.3,0.1
            Rectangle:
                size: self.size
                pos: self.pos
    BoxLayout:
        orientation: "vertical"
        size_hint: .2,1
        canvas:
            Color: 
                rgb: 0.3,0.1,0.8
            Rectangle:
                size: self.size
                pos: self.pos

        BoxLayout:
            size_hint: 1, 1
            canvas:
                Color:
                    rgb: 1,0,0.3
                Rectangle:
                    size: self.size
                    pos: self.pos
        BoxLayout:
            size_hint: 1,1
            canvas:
                Color: 
                    rgb: 0,1,0.5
                Rectangle:
                    size: self.size
                    pos: self.pos
